export const itemMappings = {
  EngramEntry_AdobeCeiling_C: "Adobe Ceiling",
  EngramEntry_AdobeGateway_C: "Adobe Dinosaur Gate",
  EngramEntry_AdobeGate_C: "Adobe Dinosaur Gateway",
  EngramEntry_AdobeDoor_C: "Adobe Door",
  EngramEntry_AdobeWallWithDoor_C: "Adobe Doorframe",
  EngramEntry_DoubleDoor_Adobe_C: "Adobe Double Door",
  EngramEntry_DoubleDoorframe_Adobe_C: "Adobe Double Doorframe",
  EngramEntry_AdobeFenceFoundation_C: "Adobe Fence Foundation",
  EngramEntry_FenceSupport_Adobe_C: "Adobe Fence Support",
  EngramEntry_AdobeFloor_C: "Adobe Foundation",
  EngramEntry_AdobeCeilingWithTrapdoor_C: "Adobe Hatchframe",
  EngramEntry_AdobeLadder_C: "Adobe Ladder",
  EngramEntry_AdobePillar_C: "Adobe Pillar",
  EngramEntry_AdobeRailing_C: "Adobe Railing",
  EngramEntry_AdobeRamp_C: "Adobe Ramp",
  EngramEntry_AdobeStairs_C: "Adobe Staircase",
  EngramEntry_Ramp_Adobe_C: "Adobe Stairs",
  EngramEntry_AdobeTrapdoor_C: "Adobe Trapdoor",
  EngramEntry_TriCeiling_Adobe_C: "Adobe Triangle Ceiling",
  EngramEntry_TriFoundation_Adobe_C: "Adobe Triangle Foundation",
  EngramEntry_TriRoof_Adobe_C: "Adobe Triangle Roof",
  EngramEntry_AdobeWall_C: "Adobe Wall",
  EngramEntry_AdobeWindow_C: "Adobe Window",
  EngramEntry_AdobeWallWithWindow_C: "Adobe Windowframe",
  EngramEntry_AdvancedBullet_C: "Advanced Bullet",
  EngramEntry_AdvancedRifleBullet_C: "Advanced Rifle Bullet",
  EngramEntry_AdvancedSniperBullet_C: "Advanced Sniper Bullet",
  EngramEntry_AirConditioner_C: "Air Conditioner",
  EngramEntry_Saddle_Allo_C: "Allosaurus Saddle",
  EngramEntry_Saddle_Amarga_C: "Amargasaurus Saddle",
  EngramEntry_AmmoBox_C: "Ammo Box",
  EngramEntry_Saddle_Ankylo_C: "Ankylo Saddle",
  EngramEntry_Saddle_Andrewsarchus_C: "Andrewsarchus Saddle",
  EngramEntry_Saddle_Spider_C: "Araneo Saddle",
  EngramEntry_Saddle_Argentavis_C: "Argentavis Saddle",
  EngramEntry_Saddle_Arthro_C: "Arthropluera Saddle",
  EngramEntry_TrophyBase_C: "Artifact Pedestal",
  EngramEntry_MachinedRifle_C: "Assault Rifle",
  EngramEntry_TekSpaceWhaleSaddle_C: "Astrocetus Tek Saddle",
  EngramEntry_SpaceDolphin_Saddle_C: "Astrodelphis Starwing Saddle",
  EngramEntry_Turret_C: "Auto Turret",
  EngramEntry_BallistaTurret_C: "Ballista Turret",
  EngramEntry_Saddle_Baryonyx_C: "Baryonyx Saddle",
  EngramEntry_BasiliskSaddle_C: "Basilisk Saddle",
  EngramEntry_Saddle_Basilosaurus_C: "Basilosaurus Saddle",
  EngramEntry_BearTrap_C: "Bear Trap",
  EngramEntry_Saddle_Toad_C: "Beelzebufo Saddle",
  EngramEntry_BeerBarrel_C: "Beer Barrel",
  EngramEntry_AdobeGate_Large_C: "Behemoth Adobe Dinosaur Gate",
  EngramEntry_AdobeGateway_Large_C: "Behemoth Adobe Dinosaur Gateway",
  EngramEntry_MetalGate_Large_C: "Behemoth Gate",
  EngramEntry_MetalGateway_Large_C: "Behemoth Gateway",
  EngramEntry_StoneGateLarge_C: "Behemoth Reinforced Dinosaur Gate",
  EngramEntry_StoneGateway_Large_C: "Behemoth Stone Dinosaur Gateway",
  EngramEntry_Tek_Gate_Large_C: "Behemoth Tek Gate",
  EngramEntry_Tek_Gategrame_Large_C: "Behemoth Tek Gateway",
  EngramEntry_BloodExtractor_C: "Blood Extraction Syringe",
  EngramEntry_Bola_C: "Bola",
  EngramEntry_Bookshelf_C: "Bookshelf",
  EngramEntry_Boomerang_C: "Boomerang",
  EngramEntry_Bow_C: "Bow",
  EngramEntry_Saddle_Sauro_Platform_C: "Bronto Platform Saddle",
  EngramEntry_Saddle_Sauro_C: "Bronto Saddle",
  EngramEntry_BugRepel_C: "Bug Repellant",
  EngramEntry_ModernBed_C: "Bunk Bed",
  EngramEntry_C4Ammo_C: "C4 Charge",
  EngramEntry_WeaponC4_C: "C4 Remote Detonator",
  EngramEntry_Camera_C: "Camera",
  EngramEntry_Campfire_C: "Campfire",
  EngramEntry_Cannon_C: "Cannon",
  EngramEntry_CannonBall_C: "Cannon Ball",
  EngramEntry_MekCannonShell_C: "Cannon Shell",
  EngramEntry_Canoe_C: "Canoe",
  EngramEntry_Canteen_C: "Canteen",
  EngramEntry_Saddle_Carcha_C: "Carcharo Saddle",
  EngramEntry_Saddle_Turtle_C: "Carbonemys Saddle",
  EngramEntry_Saddle_Carno_C: "Carno Saddle",
  EngramEntry_Saddle_Beaver_C: "Castoroides Saddle",
  EngramEntry_CatapultTurret_C: "Catapult Turret",
  EngramEntry_ChitinPaste_C: "Cementing Paste",
  EngramEntry_ChainBola_C: "Chain Bola",
  EngramEntry_ChainSaw_C: "Chainsaw",
  EngramEntry_Saddle_Chalico_C: "Chalicotherium Saddle",
  EngramEntry_ChargeBattery_C: "Charge Battery",
  EngramEntry_ChargeLantern_C: "Charge Lantern",
  EngramEntry_ChemBench_C: "Chemistry Bench",
  EngramEntry_ChitinBoots_C: "Chitin Boots",
  EngramEntry_ChitinShirt_C: "Chitin Chestpiece",
  EngramEntry_ChitinGloves_C: "Chitin Gauntlets",
  EngramEntry_ChitinHelmet_C: "Chitin Helmet",
  EngramEntry_ChitinPants_C: "Chitin Leggings",
  EngramEntry_Clay_C: "Clay",
  EngramEntry_ClimbingPick_C: "Climbing Pick",
  EngramEntry_TekCloningChamber_C: "Cloning Chamber",
  EngramEntry_ClothBoots_C: "Cloth Boots",
  EngramEntry_ClothGloves_C: "Cloth Gloves",
  EngramEntry_ClothHelmet_C: "Cloth Hat",
  EngramEntry_ClothPants_C: "Cloth Pants",
  EngramEntry_ClothShirt_C: "Cloth Shirt",
  EngramEntry_ClusterGrenade_C: "Cluster Grenade",
  EngramEntry_Compass_C: "Compass",
  EngramEntry_CompostBin_C: "Compost Bin",
  EngramEntry_CompoundBow_C: "Compound Bow",
  EngramEntry_CookingPot_C: "Cooking Pot",
  EngramEntry_Crossbow_C: "Crossbow",
  EngramEntry_CruiseMissile_C: "Cruise Missile",
  EngramEntry_CryoFridge_C: "Cryofridge",
  EngramEntry_Saddle_Daeodon_C: "Daeodon Saddle",
  EngramEntry_Saddle_Deinonychus_C: "Deinonychus Saddle",
  EngramEntry_StorageBox_Balloon_C: "Delivery Crate",
  EngramEntry_DesertClothBoots_C: "Desert Cloth Boots",
  EngramEntry_DesertClothGloves_C: "Desert Cloth Gloves",
  EngramEntry_DesertClothPants_C: "Desert Cloth Pants",
  EngramEntry_DesertClothShirt_C: "Desert Cloth Shirt",
  EngramEntry_DesertClothGooglesHelmet_C: "Desert Goggles and Hat",
  EngramEntry_DinoLeash_C: "Dino Leash",
  EngramEntry_Saddle_Desmodus_C: "Desmodus Saddle",
  EngramEntry_WoodGate_C: "Dinosaur Gate",
  EngramEntry_WoodGateway_C: "Dinosaur Gateway",
  EngramEntry_Saddle_Diplodocus_C: "Diplodocus Saddle",
  EngramEntry_Saddle_Direbear_C: "Dire Bear Saddle",
  EngramEntry_Saddle_Doed_C: "Doedicurus Saddle",
  EngramEntry_Saddle_Dunkle_C: "Dunkleosteus Saddle",
  EngramEntry_EggIncubator_C: "Egg Incubator",
  EngramEntry_ElectricProd_C: "Electric Prod",
  EngramEntry_PowerCableIntersection_C: "Electrical Cable Intersection",
  EngramEntry_PowerGenerator_C: "Electrical Generator",
  EngramEntry_PowerOutlet_C: "Electrical Outlet",
  EngramEntry_Electronics_C: "Electronics",
  EngramEntry_ElevatorTrack_C: "Elevator Track",
  EngramEntry_EmptyCryopod_C: "Cryopod",
  EngramEntry_Saddle_Equus_C: "Equus Saddle",
  EngramEntry_MachinedPistol_C: "Fabricated Pistol",
  EngramEntry_MachinedSniper_C: "Fabricated Sniper Rifle",
  EngramEntry_Fabricator_C: "Fabricator",
  EngramEntry_FeedingTrough_C: "Feeding Trough",
  EngramEntry_Fishbasket_C: "Fish Basket",
  EngramEntry_FishingNet_C: "Fish Net",
  EngramEntry_FishingRod_C: "Fishing Rod",
  EngramEntry_MetalBoots_C: "Flak Boots",
  EngramEntry_MetalShirt_C: "Flak Chestpiece",
  EngramEntry_MetalGloves_C: "Flak Gauntlets",
  EngramEntry_MetalHelmet_C: "Flak Helmet",
  EngramEntry_MetalPants_C: "Flak Leggings",
  EngramEntry_FlameArrow_C: "Flame Arrow",
  EngramEntry_Flamethrower_C: "Flamethrower",
  EngramEntry_FlamethrowerAmmo_C: "Flamethrower Ammo",
  EngramEntry_FlareLauncher_C: "Flare Gun",
  EngramEntry_Flashlight_C: "Flashlight Attachment",
  EngramEntry_Wire_Flex_C: "Flexible Electrical Cable",
  EngramEntry_FurBoots_C: "Fur Boots",
  EngramEntry_FurHelmet_C: "Fur Cap",
  EngramEntry_FurShirt_C: "Fur Chestpiece",
  EngramEntry_FurGloves_C: "Fur Gauntlets",
  EngramEntry_FurPants_C: "Fur Leggings",
  EngramEntry_GPS_C: "GPS",
  EngramEntry_GachaSaddle_C: "Gacha Saddle",
  EngramEntry_Saddle_Galli_C: "Gallimimus Saddle",
  EngramEntry_GasCollector_C: "Gas Collector",
  EngramEntry_GasMask_C: "Gas Mask",
  EngramEntry_GasBagsSaddle_C: "Gasbags Saddle",
  EngramEntry_GhillieBoots_C: "Ghillie Boots",
  EngramEntry_GhillieShirt_C: "Ghillie Chestpiece",
  EngramEntry_GhillieGloves_C: "Ghillie Gauntlets",
  EngramEntry_GhilliePants_C: "Ghillie Leggings",
  EngramEntry_GhillieHelmet_C: "Ghillie Mask",
  EngramEntry_AdobeCeilingWithDoorWay_Giant_C: "Giant Adobe Hatchframe",
  EngramEntry_AdobeCeilingDoorGiant_C: "Giant Adobe Trapdoor",
  EngramEntry_MetalCeilingWithTrapdoorGiant_C: "Giant Metal Hatchframe",
  EngramEntry_MetalTrapdoorGiant_C: "Giant Metal Trapdoor",
  EngramEntry_StoneTrapdoorGiant_C: "Giant Reinforced Trapdoor",
  EngramEntry_StoneCeilingWithTrapdoorGiant_C: "Giant Stone Hatchframe",
  EngramEntry_Saddle_Gigant_C: "Giganotosaurus Saddle",
  EngramEntry_Glider_C: "Glider Suit Skin",
  EngramEntry_Glowstick_C: "Glow Stick",
  EngramEntry_GrapplingHook_C: "Grappling Hook",
  EngramEntry_Gravestone_C: "Gravestone",
  EngramEntry_GreenhouseCeiling_C: "Greenhouse Ceiling",
  EngramEntry_GreenhouseDoor_C: "Greenhouse Door",
  EngramEntry_GreenhouseWallWithDoor_C: "Greenhouse Doorframe",
  EngramEntry_DoubleDoor_Greenhouse_C: "Greenhouse Double Door",
  EngramEntry_DoubleDoorframe_Greenhouse_C: "Greenhouse Double Doorframe",
  EngramEntry_TriCeiling_Greenhouse_C: "Greenhouse Triangle Ceiling",
  EngramEntry_TriRoof_Greenhouse_C: "Greenhouse Triangle Roof",
  EngramEntry_GreenhouseWall_C: "Greenhouse Wall",
  EngramEntry_GreenhouseWindow_C: "Greenhouse Window",
  EngramEntry_Grenade_C: "Grenade",
  EngramEntry_Gunpowder_C: "Gunpowder",
  EngramEntry_Handcuffs_C: "Handcuffs",
  EngramEntry_HarpoonGun_C: "Harpoon Launcher",
  EngramEntry_HazardSuit_Boots_C: "Hazard Suit Boots",
  EngramEntry_HazardSuit_Gloves_C: "Hazard Suit Gloves",
  EngramEntry_HazardSuit_Helmet_C: "Hazard Suit Hat",
  EngramEntry_HazardSuit_Pants_C: "Hazard Suit Pants",
  EngramEntry_HazardSuit_Chest_C: "Hazard Suit Shirt",
  EngramEntry_HeavyTurret_C: "Heavy Auto Turret",
  EngramEntry_MinersHelmet_C: "Heavy Miner's Helmet",
  EngramEntry_HideBoots_C: "Hide Boots",
  EngramEntry_HideGloves_C: "Hide Gloves",
  EngramEntry_HideHelmet_C: "Hide Hat",
  EngramEntry_HidePants_C: "Hide Pants",
  EngramEntry_HideShirt_C: "Hide Shirt",
  EngramEntry_HideSleepingBag_C: "Hide Sleeping Bag",
  EngramEntry_HoloScope_C: "Holo-Scope Attachment",
  EngramEntry_SeaMine_C: "Homing Underwater Mine",
  EngramEntry_Saddle_Hyaenodon_C: "Hyaenodon Meatpack",
  EngramEntry_Saddle_Dolphin_C: "Ichthyosaurus Saddle",
  EngramEntry_Saddle_Iguanodon_C: "Iguanodon Saddle",
  EngramEntry_TripwireC4_C: "Improvised Explosive Device",
  EngramEntry_PowerCableIncline_C: "Inclined Electrical Cable",
  EngramEntry_IndustrialCookingPot_C: "Industrial Cooker",
  EngramEntry_IndustrialForge_C: "Industrial Forge",
  EngramEntry_Grill_C: "Industrial Grill",
  EngramEntry_Grinder_C: "Industrial Grinder",
  EngramEntry_Boulder_Fire_C: "Jar of Pitch",
  EngramEntry_Saddle_Kaprosuchus_C: "Kaprosuchus Saddle",
  EngramEntry_KarkinoSaddle_C: "Karkinos Saddle",
  EngramEntry_Lamppost_C: "Lamppost",
  EngramEntry_Lance_C: "Lance",
  EngramEntry_LargeWall_Adobe_C: "Large Adobe Wall",
  EngramEntry_BearTrap_Large_C: "Large Bear Trap",
  EngramEntry_CropPlot_Large_C: "Large Crop Plot",
  EngramEntry_ElevatorPlatformLarge_C: "Large Elevator Platform",
  EngramEntry_LargeWall_Metal_C: "Large Metal Wall",
  EngramEntry_LargeWall_Stone_C: "Large Stone Wall",
  EngramEntry_StorageBox_Large_C: "Large Storage Box",
  EngramEntry_TaxidermyBase_Large_C: "Large Taxidermy Base",
  EngramEntry_LargeWall_Tek_C: "Large Tek Wall",
  EngramEntry_WoodElevatorPlatform_Large_C: "Large Wood Elevator Platform",
  EngramEntry_LargeWall_Wood_C: "Large Wooden Wall",
  EngramEntry_Laser_C: "Laser Attachment",
  EngramEntry_CureLow_C: "Lesser Antidote",
  EngramEntry_LoadoutMannequin_C: "Loadout Mannequin",
  EngramEntry_SimpleRifle_C: "Longneck Rifle",
  EngramEntry_Saddle_Moth_C: "Lymantria Saddle",
  EngramEntry_MekBackpack_Shield_C: "M.D.S.M.",
  EngramEntry_MekBackpack_Missiles_C: "M.R.L.M.",
  EngramEntry_MekBackpack_Cannon_C: "M.S.C.M.",
  EngramEntry_Milkglider_Saddle_C: "Maewing Saddle",
  EngramEntry_CherufeSaddle_C: "Magmasaur Saddle",
  EngramEntry_MagnifyingGlass_C: "Magnifying Glass",
  EngramEntry_Saddle_Mammoth_C: "Mammoth Saddle",
  EngramEntry_IceJumperSaddle_C: "Managarmr Saddle",
  EngramEntry_Saddle_Manta_C: "Manta Saddle",
  EngramEntry_Saddle_Mantis_C: "Mantis Saddle",
};
